- color: e89c5f
  description: Something isn't working
  name: bug
- color: 0075ca
  description: Improvements or additions to documentation
  name: documentation
- color: cfd3d7
  description: This issue or pull request already exists
  name: duplicate
- color: e4e669
  description: This doesn't seem right
  name: invalid