name: Action Test GitHub Actions Versioning
description: Test GitHub Actions versioning
author: micnncim
inputs:
  github_token:
    description: A GitHub token to create an issue comment
    required: true
  repository:
    description: A repository
    required: false
    default: ${{ github.repository }}
  number:
    description: An issue number
    required: false
    default: ${{ github.event.issue.number }}
runs:
  using: docker
  image: Dockerfile
