#!/bin/sh

set -e

export STARDUST_GITHUB_TOKEN=${INPUT_GITHUB_TOKEN}
export STARDUST_GITHUB_USERNAME=${INPUT_GITHUB_USERNAME}
export STARDUST_SLACK_ENABLED=${INPUT_SLACK_ENABLED}
export STARDUST_SLACK_TOKEN=${INPUT_SLACK_TOKEN}
export STARDUST_SLACK_CHANNEL=${INPUT_SLACK_CHANNEL}
export STARDUST_LOG_LEVEL=${INPUT_LOG_LEVEL}
export STARDUST_INTERVAL=${INPUT_INTERVAL}

stardust
