name: Actions Ecosystem Action Get Latest Tag
description: Get a latest Git tag.
author: Actions Ecosystem
inputs:
  semver_only:
    description: Whether gets only a tag in the shape of semver. 'v' prefix is accepted.
    required: false
    default: "false"
outputs:
  tag:
    description: The latest tag.
runs:
  using: docker
  image: Dockerfile
branding:
  icon: bookmark
  color: green
