name: Generate Spinnaker Swagger schema

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 13

    - name: Generate Swagger schema
      run: |
        git clone https://github.com/spinnaker/gate.git
        cd gate
        git switch --detach version-1.18.1
        ./swagger/generate_swagger.sh
        cat ./swagger/swagger.json
