name: Lint Issue Title

on:
  issues:
    types:
      - opened
      - edited

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.issue.title }}
          regex: '(?:add|update|fix)\([a-z]+\):\s.+'

      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ steps.regex-match.outputs.match == '' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            :warning: The title of this PR is invalid.

            Please make the title match the regex `(?:add|update|fix)\([a-z]+\):\s.+`.

            e.g.) `add(cli): enable --verbose flag`, `fix(api): avoid unexpected error in handler`

      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.regex-match.outputs.match == '' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'invalid/title'

      - if: ${{ steps.regex-match.outputs.match == '' }}
        run: exit 1
