name: Push Git Tag

on:
  issue_comment:
    types: [created]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action-push-tag
        if: ${{ startsWith(github.event.comment.body, '/push-tag') }}
        with:
          tag: v1.2.1
          message: test
