name: Release Label

on:
  pull_request:
    types: [closed]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action-release-label
