name: Stardust

on:
  schedule:
    - cron: "0 9 * * 0" # At 09:00 on Sunday
  issue_comment:
    types:
      - created

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/action-stardust
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: micnncim
          interval: 168h
          slack_enabled: true
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel: github-star
