name: Actions Ecosystem Add Labels
description: Add labels to an issue or a pull request.
author: The Actions Ecosystem Authors
inputs:
  slack_token:
    description: A Slack token.
    required: true
  message:
    description: A message for channel.
    required: true
  channel:
    description: The labels' name to be added. Must be separated with line breaks if there're multiple labels.
    required: true
  username:
    description: The username who sends a message.
    required: false
    default: 'GitHub Actions'
runs:
  using: node12
  main: dist/index.js
branding:
  icon: bookmark
  color: green
