name: Add Labels

on: [issues, issue_comment, pull_request, pull_request_review, pull_request_review_comment]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action-add-labels
        with:
          github_token: ${{ secrets.github_token }}
          labels: ''