name: Add Label

on:
  issues:
    types: [opened]

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action-add-labels
        with:
          github_token: ${{ secrets.github_token }}
          label: '["enhancement"]'
