name: Auto Assign

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/action-add-assignees
        with:
          github_token: ${{ secrets.github_token }}
          assignees: ${{ github.actor }}
