name: Add Labels

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action-add-labels
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            enhancement
            bug
