name: Check Functions

on:
  issue_comment:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - env:
          LABEL_NAMES: ${{ github.event.issue.labels.*.name }}
        run: echo "${LABEL_NAMES}"
