name: Check Functions

on:
  issue_comment:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ github.event.issue.labels.*.name }}
      - run: echo ${{ contains(github.event.issue.labels.*.name, 'bug') }}
