name: Dump GitHub Context

on:
  issue_comment: [created]
  pull_request_review_comment: [created]
jobs:
  build:
    name: Dump GitHub Context
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
