name: Dump GitHub Event Path Content

on: 
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
jobs:
  build:
    name: Dump GitHub Event Path Content
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install jq
      - run: echo $GITHUB_EVENT_PATH
      - run: cat ${GITHUB_EVENT_PATH}
