name: Echo token

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          export KEY=VALUE
          echo ${KEY}
      - run: echo ${GITHUB_TOKEN}
      - run: echo ${{ secrets.GITHUB_TOKEN }}
  