name: Get Latest Tag

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [synchronize]
  push:

jobs:
  get_latest_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action-get-latest-tag
