name: Get Latest Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  get_latest_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action-get-latest-tag
