name: GitHub Context JSON
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
      - uses: ./action-github-context-json
        env:
          GITHUB: ${{ github }}
