name: Test GitHub Actions Versioning

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/github-actions-lab@v1.1.0
        if: ${{ startsWith(github.event.comment.body, '/latest-release') }}
        with:
          github_token: ${{ secrets.github_token }}
