name: Send LGTM reaction
on:
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
      - uses: micnncim/action-lgtm-reaction@0.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_COMMENT_BODY: ${{ github.event.comment.body }}
          GITHUB_COMMENT_ID: ${{ github.event.comment.id }}
          GITHUB_ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_REVIEW_BODY: ${{ github.event.review.body }}
          GITHUB_REVIEW_ID: ${{ github.event.review.id }}
        with:
          override: true
