name: Lint Commits

on:
  pull_request_target:
    types: ["opened", "reopened", "synchronize"]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/action-lint-commits
        id: lint-commits
        with:
          github_token: ${{ secrets.github_token }}
          regex: '^\w+\(.+\): .+' # e.g.) "feat(api): Add /users/get"
          format: markdown

      - uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            The following commits needs their message changes:

            ${{ steps.lint-commits.outputs.unmatched_commits }}

            The format `<type>(<scope>): <subject>` (`^\w+\(.+\): .+`) is acceptable. e.g., `feat(api): Add /users/get`
