name: Lint PR Title

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '(?:add|update|fix)\([a-z]+\):\s.+'

      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            The title of this pull request is invalid. Please make the title match `(?:add|update|fix)\([a-z]+\):\s.+`.
            Good examples are `add(cli): enable --verbose flag` and `fix(api): avoid unexpected error in handler`
