name: Create Comment with Regex Match TypeScript

on: [issue_comment]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action-regex-match-ts
        id: regex-match
        with:
          text: ${{ github.event.comment.body }}
          regex: '```release_note([\s\S]*)```'
          flags: gm
      - uses: ./.github/actions/action-create-comment
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Hello, @${{ github.actor }}!

            The raw release note is here.
            ---
            ${{ steps.regex-match.outputs.group1 }} 
            ---

            *This message has been sent via actions-ecosystem/action-regex-match-ts.*
