name: Release Label

on:
  pull_request:
    types: [labeled]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action-release-label
        id: release-label
      - uses: ./.github/actions/action-create-comment
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Hello, @${{ github.actor }}!
            The semver update level of the release label: ${{ steps.release-label.outputs.level }}

            *This message has been sent via actions-ecosystem/action-create-comment.*
