name: Remove Labels

on: [issue_comment]

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action-remove-labels
        if: ${{ startsWith(github.event.comment.body, '/remove-labels') }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            enhancement
            bug
