name: Size

on:
  pull_request:
    types: [synchronize]

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/size-ts
        with:
          github_token: ${{ secrets.github_token }}
          dry_run: true
