name: Slack Notify

on: [issue_comment]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.comment.body }}
          regex: '\B@(?!.*(-){2,}.*|.*\/.*)[a-z0-9](?:[a-z0-9-]{0,37}[a-z0-9])?\b'

      - uses: ./.github/actions/action-slack-notify
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel: dev
          message: ${{ steps.regex-match.outputs.match }}
          color: cyan
          verbose: true
