name: Slack Notifier

on:
  # issue_comment:
  # issues:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: ./.github/actions/action-slack-notifier
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          message: 'Test for _good_ color'
          channel: dev
          color: yellow # optional
          verbose: true # optional
