name: Slack Notifier

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/action-slack-notifier
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          message: Hello
          channel: dev
          color: blue # optional
          verbose: true # optional
          custom_payload: |
            [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "> message *with some bold text* and _some italicized text_."
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "This is a mrkdwn section block :ghost: *this is bold*, and ~this is crossed out~, and <https://google.com|this is a link>"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "plain_text",
                  "text": "This is a plain text section block.",
                  "emoji": true
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "For more info, contact <support@acme.inc>"
                  }
                ]
              }
            ]
