name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-ecosystem/action-set-action-status@v1
        with:
          status: failure
          
      - uses: ./.github/actions/action-slack-notifier
        if: ${{ always() }}
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          message: |
            @{{ github.actor }} test failed.
          channel: develop
          color: red # optional
          verbose: true # optional
