name: Slack Notifier

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/action-slack-notifier
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          message: Hello
          channel: dev
          color: blue # optional
          verbose: true # optional
