name: Propagate Comment

on:
  issue_comment:
  issues:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-ecosystem/action-regex-match@v1
        id: regex-match
        with:
          text: ${{  }}
          regex: '\B@(?!.*(-){2,}.*|.*\/.*)[a-z0-9](?:[a-z0-9-]{0,37}[a-z0-9])?\b'
          
      - uses: ./.github/actions/action-slack-notifier
        if: ${{ failure() }}
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          message: |
            @${{ github.actor }} mentioned 
          channel: dev
          color: blue # optional
          verbose: true # optional
