name: Slack Notifier

on:
  issue_comment:
    types:
      - created

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          regex: '\/cc(?:( +@[-\w]+?)+)\s'
          text: ${{ github.event.comment.body }}

      - uses: ./.github/actions/action-slack-notifier
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          message: |
            `${{ steps.regex-match.outputs.group1 }}` are mentioned.
          channel: dev
          color: blue # optional
          verbose: true # optional
