name: Slack Notify

on:
  issue_comment:
  issues:
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/action-slack-notify
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          message: '@micnncim Hello'
          channel: dev
          color: green
          verbose: true
